### ISSUE TITLE
Remove symfony services

### ISSUE THREAD

**Issue by migo315** [bestit/contentful-symfony-bundle#16]
Currently default symfony services are used, like "event_dispatcher" or "logger".

```
    best_it_contentful.delivery.client:
        class: BestIt\ContentfulBundle\Service\Delivery\ClientDecorator
        arguments:
            - '@contentful.delivery'
            - '@best_it_contentful.cache.pool.delivery'
            - '@event_dispatcher'
            - '@logger'
            - '@best_it_contentful.delivery.response_parser.default'
        calls:
            - [setCacheTTL, ['%best_it_contentful.cache.content.cache_ttl%']]
            - [setRoutableTypes, ['%best_it_contentful.routable_types%']]
            - [setSlugField, ['%best_it_contentful.routing_field%']]
```

You should always provide the possibility for using another service. Instead of using this service id directly, just use an alias like "best_it_contentful.event_dispatcher". Create a configuration field for setting a event disptacher service id and set "event_dispatcher" as default. That's no breaking change.
